### ISSUE TITLE
<dependencyManagement> is not added to pom.xml when spring-io is applied

### ISSUE THREAD

**Issue by rwinch** [spring-gradle-plugins/spring-io-plugin#5]
This issue supersedes https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/169

When the spring-io-plugin is applied to a project that also has the dependency management plugin, the `<dependencyManagement>` section of the pom is no longer added using Gradle 3.5. For example:

```groovy
buildscript {
	dependencies {
		classpath 'io.spring.gradle:spring-io-plugin:0.0.7.BUILD-SNAPSHOT'
		classpath 'io.spring.gradle:dependency-management-plugin:1.0.3.BUILD-SNAPSHOT'
	}
	repositories {
		maven { url 'https://repo.spring.io/plugins-release' }
		maven { url 'https://repo.spring.io/plugins-snapshot' }
	}
}

apply plugin: 'java'
// comment out spring-io plugin below and the <dependencyManagement> section is generated
apply plugin: 'spring-io'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'maven'

repositories {
	mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'io.spring.platform:platform-bom:1.1.1.RELEASE'
    }
}

dependencies {
	compile 'org.springframework:spring-core'
}
```

Run 

```bash
$ gradle install
$ cat build/poms/pom-default.xml                                          
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId/>
  <artifactId>gradle-dependency-management-bug</artifactId>
  <version>unspecified</version>
  <dependencies>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

If you comment out the spring-io plugin the `<dependencyMangement>` section is rendered.

This appears to be an issue with the spring-io-plugin which [disables](https://github.com/spring-gradle-plugins/spring-io-plugin/blob/029d8757df6b8b09da3ea5bd1a1ca3e977d24a57/src/main/java/io/spring/gradle/springio/SpringIoPlugin.java#L55) `GeneratedPomCustomizationHandler`. If this line is commented out, then the `<dependencyManagement>` is rendered properly.

**Comment by wilkinsona** [comment]
Ah, yes. I remember now. That's intentional as we don't want a project's pom to be inadvertently configured with the Platform's dependency management.

I'm not sure what we can do about this. The recommended way to use this plugin is to only apply it when running a Platform compatibility build but I guess you have a need to apply it all the time. I think we'll need to explore your setup a bit and see if we can find a balance.

**Comment by rwinch** [comment]
Hmm...I wonder if this is really a problem since spring platform is a different configuration that isn't exported to the pom? Perhaps we can make the `GeneratedPomCustomizationHandler` configuration per configuration as an alternative?

**Comment by rwinch** [comment]
Thanks!
